#!/usr/bin/env python3
"""Render pkg/toml/bench/out/{bit,burntsushi,gotoml}.{rs,ms} as the README
block run.sh injects between pkg/toml/README.md's BENCH markers (#5488).

THE BLOCK IS GENERATED, NEVER HAND-EDITED, the same contract every other
bench/run.sh in this repo holds: the block says so itself, and the next run
overwrites whatever is between the markers.

Trimmed mean (drop the slowest fifth of RUNS samples, mean what is left) is
the same estimator run.sh's own trimmean() uses to build these files -
bench/run.sh:34-59 (repo root, #4040) settled on it after comparing four.
"""
import os
import sys


def trimmean(vals):
    vals = sorted(vals)
    k = max(1, len(vals) // 5)
    kept = vals[: len(vals) - k]
    return sum(kept) / len(kept)


def load(out_dir, name):
    rs = [float(x) for x in open(os.path.join(out_dir, f"{name}.rs"))]
    ms = [float(x) for x in open(os.path.join(out_dir, f"{name}.ms"))]
    return trimmean(rs), trimmean(ms)


def main():
    out_dir, fixture, commit, stamp, bitver, goversion, host, runs, bsver, gtver = sys.argv[1:11]
    fixture_bytes = os.path.getsize(fixture)

    rows = []
    for name, label in [
        ("bit", "pkg/toml"),
        ("burntsushi", "BurntSushi/toml"),
        ("gotoml", "go-toml/v2 (pelletier)"),
    ]:
        secs, rss_bytes = load(out_dir, name)
        mb_s = fixture_bytes / secs / 1_000_000
        rss_mb = rss_bytes / 1_048_576
        rows.append((label, mb_s, rss_mb))

    base_mb_s = rows[0][1]

    print("## Benchmarks")
    print()
    print(
        f"Parse throughput against the two Go TOML libraries in wide use, over "
        f"the same {fixture_bytes / 1_048_576:.2f} MB checked-in fixture "
        f"(`bench/data/fixture.toml`, a Cargo-manifest shape scaled up with "
        f"tables, arrays of tables, inline tables, dotted keys, all four "
        f"TOML 1.0.0 date-time forms and multi-line strings). All three sides "
        f"parsed it to a byte-identical checksum before anything was timed "
        f"(entry count + a CRC-32C fold over every key and scalar value, "
        f"sorted by key so an unordered Go map iterates the same as pkg/toml's "
        f"source-ordered table) - see `RESULTS.md`'s own verification "
        f"transcript below."
    )
    print()
    print("| Implementation | MB/s | Peak RSS | vs pkg/toml |")
    print("|---|--:|--:|--:|")
    for label, mb_s, rss_mb in rows:
        ratio = mb_s / base_mb_s if base_mb_s else 0.0
        print(f"| {label} | {mb_s:,.1f} | {rss_mb:,.1f} MB | {ratio:.2f}x |")
    print()
    print(
        f"> Each figure is the trimmed mean (slowest fifth of {runs} runs "
        f"dropped, mean of the rest) of one process invocation: read the "
        f"fixture, parse it once, print an entry count, exit - never the "
        f"checksum walk above, which is a separate, untimed mode of the same "
        f"binary (folding and sorting the whole tree on every timed run would "
        f"measure parse+hash throughput, not parse throughput). `vs pkg/toml` "
        f"divides that implementation's MB/s by pkg/toml's own."
    )
    print(
        f"> Peak RSS is `/usr/bin/time -l`'s \"maximum resident set size\" for "
        f"that same process, trimmed the same way."
    )
    print(
        f"> Both Go competitors are cross-compiled for this host's own "
        f"OS/arch inside a throwaway `docker run` (never installed on the "
        f"host) and then run natively, exactly like pkg/toml's own binary - "
        f"never timed from inside the container, which would fold Docker "
        f"Desktop's VM overhead into one side of the comparison and not the "
        f"other."
    )
    print(
        f"> Versions: compiler {bitver} (released), {goversion}, BurntSushi/toml {bsver}, "
        f"go-toml/v2 {gtver}."
    )
    print(f"> Host: {host}.")
    print(
        f"> Generated by `pkg/toml/bench/run.sh` from pkg/toml at `{commit}` on "
        f"{stamp}. Do not edit by hand."
    )


if __name__ == "__main__":
    main()
