#!/usr/bin/env python3
"""Writes data/config.toml, pkg/toml/bench's second fixture (#6048).

fixture.toml is one Cargo-manifest shape repeated; this one stresses what
service configs are made of instead: thousands of small [a.b.c] tables,
long basic strings dense with escapes, and big arrays of integers and
floats. Deterministic (a fixed LCG, not `random`, whose sequence is not a
stable contract across Python releases), run once by hand, output checked
in: a fixture that changes per run cannot be compared across commits.

TOML 1.0.0 only (no \\e, no \\x, no seconds-less times), so every peer
agrees on validity. Fractional seconds stop at six digits: tomlc17 keeps
microseconds, and a seventh digit would register as a checksum mismatch
that is a representation limit, not a parse error.

    python3 pkg/toml/bench/data/gen_config.py > pkg/toml/bench/data/config.toml
"""
import sys

SERVICES = 1000
REGIONS = ["eu-west-1", "us-east-2", "ap-south-1", "sa-east-1"]
WORDS = ["alpha", "bravo", "charlie", "delta", "echo", "foxtrot", "golf",
         "hotel", "india", "juliet", "kilo", "lima"]


class Lcg:
    def __init__(self, seed):
        self.s = seed

    def next(self, n):
        self.s = (self.s * 6364136223846793005 + 1442695040888963407) % (1 << 64)
        return (self.s >> 33) % n


def banner(r, i):
    """A long basic string: every TOML 1.0 escape, several times over."""
    parts = []
    for k in range(6):
        w = WORDS[r.next(len(WORDS))]
        parts.append("%s-%04d\\t\\\"%s\\\" path C:\\\\srv\\\\%s\\\\%d\\n" % (w, i, w.upper(), w, k))
        parts.append("caf\\u00e9 na\\u00efve \\U0001F600 bell\\b form\\f cr\\r ")
    return "".join(parts)


def ints(r, n):
    out = []
    for _ in range(n):
        v = r.next(2000000) - 1000000
        pick = r.next(8)
        if pick == 0 and v > 0:
            out.append("0x%x" % v)
        elif pick == 1 and v > 999:
            s = str(v)
            out.append(s[:-3] + "_" + s[-3:])
        else:
            out.append(str(v))
    return out


def floats(r, n):
    out = []
    for _ in range(n):
        m = r.next(2000000) - 1000000
        e = r.next(9) - 4
        out.append("%d.%03de%d" % (m // 1000, abs(m) % 1000, e) if r.next(3) == 0
                   else "%d.%04d" % (m // 10000, abs(m) % 10000))
    return out


def service(r, i):
    name = "svc%04d" % i
    region = REGIONS[r.next(len(REGIONS))]
    tags = ", ".join('"%s"' % WORDS[r.next(len(WORDS))] for _ in range(3))
    w = [
        "",
        "[service.%s]" % name,
        'name = "%s"' % name,
        "enabled = %s" % ("true" if r.next(2) else "false"),
        "port = %d" % (8000 + i),
        "replicas = %d" % (1 + r.next(9)),
        'region = "%s"' % region,
        "tags = [%s]" % tags,
        'banner = "%s"' % banner(r, i),
        "deployed = 2026-0%d-1%dT0%d:1%d:2%d.%06d+0%d:30" % (
            1 + r.next(9), r.next(10), r.next(10), r.next(10), r.next(10),
            r.next(1000000), r.next(10)),
        "",
        "[service.%s.limits]" % name,
        "cpu = %d" % (100 * (1 + r.next(40))),
        "memory = %d" % (256 * (1 + r.next(64))),
        "timeouts = { connect = %d, read = %d, write = %d }" % (
            1 + r.next(10), 10 + r.next(50), 10 + r.next(50)),
        "",
        "[service.%s.metrics]" % name,
        "samples = [%s]" % ", ".join(ints(r, 48)),
        "weights = [%s]" % ", ".join(floats(r, 16)),
    ]
    return "\n".join(w)


def main():
    r = Lcg(6048)
    out = sys.stdout
    out.write("# Synthetic service-config TOML fixture for pkg/toml/bench (#6048).\n")
    out.write("# Generated by data/gen_config.py; checked in, never regenerated at run time.\n\n")
    out.write('[meta]\nschema = 3\nowner = "platform"\ngenerated = 2026-09-27\n')
    for i in range(SERVICES):
        out.write(service(r, i))
        out.write("\n")
    out.write("\n[matrix]\n")
    for row in range(40):
        out.write("row%02d = [%s]\n" % (row, ", ".join(ints(r, 400))))


main()
