#!/usr/bin/env bash
# Differential harness for the Stage-2 allocator port (#1362): runtime/alloc.zig
# vs runtime/alloc.bit.
#
# Both implementations are driven over the SAME request sequence and their
# answers are diffed byte for byte. Nothing here is a stored golden — each run
# re-derives both sides from the two sources, so the harness cannot go stale and
# cannot pass because someone updated an expectation.
#
# It compares the three properties the collector's correctness rests on:
#
#   class    — all 37 size classes. `alloc.bit` COMPUTES this table where the
#              Zig spells it as a literal array (a `@nosplit` body cannot index
#              a table: a bracket literal is a slice and slice indexing lowers
#              to `bit_rt_slice_get`, E0075). That substitution is the single
#              highest-risk line of the port, and this is what pins it.
#   classify — the size-class chosen for a (size, alignment) matrix that spans
#              both the small and the direct-mapped paths, including the
#              boundary at max_small and alignments up to 16384.
#   alignup / nonzero / largelen — the arithmetic the alignment guarantee and
#              the large-path mapped length are built from.
#
# The Zig side is compiled from a COPY of runtime/alloc.zig with a `main`
# appended, which is how the file-private `classify`, `class_sizes`, `alignUp`
# and `nonZero` are reachable at all: appended code sits inside the same file,
# so no `pub` is added and the shipped source is never modified.
#
# Usage: bash scripts/alloc-difftable.sh
# Exit 0 on a byte-identical match, 1 otherwise.

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Staged inside the repo, not /tmp: a Bit import path must be relative (E0045),
# so the generated driver has to sit at a known depth below the repo root to
# reach `runtime/`. Removed on exit.
work="$root/.tmp-allocdiff"
rm -rf "$work"
mkdir -p "$work"
trap 'rm -rf "$work"' EXIT

bit="$root/zig-out/bin/bit-seed"
[ -x "$bit" ] || { echo "alloc-difftable: $bit missing (run: zig build)" >&2; exit 1; }

# --- the shared request sequence, generated identically on both sides --------
# size walk: s = 1; s += s/2 + 1   -- integer-only, so both languages agree.
# alignments: 8 .. 16384 by doubling.

# --- Zig side ----------------------------------------------------------------
mkdir -p "$work/zig"
cp "$root/runtime/alloc.zig" "$work/zig/alloc.zig"
cp "$root/runtime/spinlock.zig" "$work/zig/spinlock.zig"

cat >> "$work/zig/alloc.zig" <<'ZIGMAIN'

// ---- appended by scripts/alloc-difftable.sh (not part of the shipped file) --
pub fn main() void {
    var i: usize = 0;
    while (i < num_classes) : (i += 1) {
        std.debug.print("class {d} {d}\n", .{ i, class_sizes[i] });
    }

    var a: usize = 8;
    while (a <= 16384) : (a *= 2) {
        var s: usize = 1;
        while (s <= 20000) : (s += s / 2 + 1) {
            const r = classify(s, a);
            const idx: i64 = if (r) |v| @intCast(v) else -1;
            std.debug.print("classify {d} {d} {d}\n", .{ s, a, idx });
        }
    }

    var a2: usize = 8;
    while (a2 <= 16384) : (a2 *= 2) {
        var n: usize = 0;
        while (n <= 20000) : (n += n / 2 + 1) {
            std.debug.print("alignup {d} {d} {d}\n", .{ n, a2, alignUp(n, a2) });
            if (n == 0) continue;
        }
    }

    var n2: usize = 0;
    while (n2 <= 4) : (n2 += 1) {
        std.debug.print("nonzero {d} {d}\n", .{ n2, nonZero(n2) });
    }

    for ([_]usize{ 4096, 16384 }) |ps| {
        var s2: usize = 0;
        while (s2 <= 1200000) : (s2 += s2 / 2 + 1) {
            std.debug.print("largelen {d} {d} {d}\n", .{ s2, ps, alignUp(nonZero(s2), ps) });
        }
    }
}
ZIGMAIN

zig build-exe "$work/zig/alloc.zig" -O ReleaseSafe -femit-bin="$work/zigdump" >/dev/null
"$work/zigdump" 2> "$work/zig.txt"

# --- Bit side ----------------------------------------------------------------
mkdir -p "$work/bit"
cat > "$work/bit/main.bit" <<'BITMAIN'
// Generated by scripts/alloc-difftable.sh. Drives runtime/alloc.bit over the
// same request sequence the appended Zig main drives runtime/alloc.zig over.
import {
  allocNumClasses, allocClassSize, allocClassify, allocAlignUp, allocNonZero,
  allocLargeLen,
} from "../../runtime/alloc"

function main() {
  let out = ""

  let i = 0
  while (i < allocNumClasses) {
    out = out + "class ${i} ${allocClassSize(i)}\n"
    i = i + 1
  }

  let a = 8
  while (a <= 16384) {
    let s = 1
    while (s <= 20000) {
      out = out + "classify ${s} ${a} ${allocClassify(s, a)}\n"
      s = s + s / 2 + 1
    }
    a = a * 2
  }

  let a2 = 8
  while (a2 <= 16384) {
    let n = 0
    while (n <= 20000) {
      out = out + "alignup ${n} ${a2} ${allocAlignUp(n, a2)}\n"
      n = n + n / 2 + 1
    }
    a2 = a2 * 2
  }

  let n2 = 0
  while (n2 <= 4) {
    out = out + "nonzero ${n2} ${allocNonZero(n2)}\n"
    n2 = n2 + 1
  }

  let pi = 0
  while (pi < 2) {
    let ps = 4096
    if (pi == 1) { ps = 16384 }
    let s2 = 0
    while (s2 <= 1200000) {
      out = out + "largelen ${s2} ${ps} ${allocLargeLen(s2, ps)}\n"
      s2 = s2 + s2 / 2 + 1
    }
    pi = pi + 1
  }

  print(out)
}
BITMAIN

"$bit" build "$work/bit" -o "$work/bitdump" >/dev/null
"$work/bitdump" > "$work/bit.txt"

# --- compare -----------------------------------------------------------------
zl=$(wc -l < "$work/zig.txt" | tr -d ' ')
bl=$(wc -l < "$work/bit.txt" | tr -d ' ')

if diff -u "$work/zig.txt" "$work/bit.txt" > "$work/diff.txt"; then
  echo "alloc differential: MATCH records=$zl (zig=$zl bit=$bl) DIFF=0"
  exit 0
fi

echo "alloc differential: MISMATCH zig=$zl bit=$bl"
head -40 "$work/diff.txt"
exit 1
