#!/bin/sh
# Deploys website/public/ to bit-lang.byteink.com on the byteink k3s cluster.
# Regenerates the page first, so a deploy can never ship a stale support matrix.
#
# Prerequisite outside this repo: a DNS record for bit-lang.byteink.com pointing
# at the cluster. Traefik answers on the `websecure` entrypoint and gets the
# certificate from the `letsencrypt` resolver, so nothing else is needed.
set -eu

ctx=${BIT_KUBE_CONTEXT:-byteink}
ns=${BIT_KUBE_NAMESPACE:-byteink}
root=$(unset CDPATH; cd -- "$(dirname -- "$0")/.." && pwd)

command -v kubectl >/dev/null || { echo "deploy.sh: kubectl not found" >&2; exit 1; }

sh "$root/website/support.sh"

# --dry-run | apply, because `kubectl create configmap` is not idempotent and
# `--from-file` on a directory is the only thing that keeps the served bytes and
# the generated bytes identical.
kubectl --context "$ctx" -n "$ns" create configmap bit-lang-site \
	--from-file "$root/website/public" \
	--dry-run=client -o yaml | kubectl --context "$ctx" apply -f -

kubectl --context "$ctx" apply -f "$root/website/deploy/bit-lang.yaml"

# The ConfigMap changed but the pod spec did not, so nothing would restart on its
# own; kubelet's own ConfigMap refresh is minutes-late and silent.
kubectl --context "$ctx" -n "$ns" rollout restart deployment/bit-lang
kubectl --context "$ctx" -n "$ns" rollout status deployment/bit-lang --timeout=120s

echo "deploy.sh: https://bit-lang.byteink.com/support.html"
